apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
    - "*"
  gateways:
    - kubeflow/kubeflow-gateway
  http:
    - match:
        - uri:
            exact: /notebooks
      rewrite:
        uri: "/"
      route:
        - destination:
            host: nb-frontend.kubeflow-system.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            regex: /notebooks/(?!api/).*
      rewrite:
        uri: "/"
      route:
        - destination:
            host: nb-frontend.kubeflow-system.svc.cluster.local
            port:
              number: 8080